### ISSUE TITLE
placeholder class is wrongly made

### ISSUE THREAD

**Issue by MassiveLag** [nulli0n/CoinsEngine-spigot#1]
The first placeholder works fine %coinsengine_balance_<name>% but when you use raw and so on, it won't work. This is because of the check you use it always gets the first currency name due you co startsWith("balance_") the other plugins also starts with this.

**Comment by smashyalts** [comment]
having same issue, would appreciate it being fixed :D

**Comment by nulli0n** [comment]
Fixed in latest update.
