### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by kokqi** [nulli0n/CoinsEngine-spigot#14]
implement check for /crates key give `amount`

like so it could prevent further key give if detected player inventory can't fit those item just like what I did with a math expansion but I couldn't prevent the `amount` with Math expansion so ya consider implement
https://streamable.com/7jr6ui

============================
implement formatting

formatting:
      thousands: k
      millions: M
      billions: B
      trillions: T
      quadrillions: Q

implement something like %vault_eco_balance_formatted% (don't show the decimals) https://cdn.discordapp.com/attachments/960838933124636672/1185784412500135966/image.png?ex=6590deca&is=657e69ca&hm=6ffc673f63982e8b417da54e35fb6ab527e06da87afe67699df2e11ed6c3a851&

**Comment by nulli0n** [comment]
Formating is available in v2.2.0.
