### ISSUE TITLE
Leaderboards not updating right away

### ISSUE THREAD

**Issue by Tonierbobcat** [nulli0n/CoinsEngine-spigot#16]
If I give myself money and use/baltop it does not update rightaway and I have to restart the server
same goes for the top_balance placeholders

**Comment by OrangeHCZ** [comment]
The variable of PlaceholderAPI also has this issue. I guess it's because the currency data is not updated in a timely manner. I hope the author can solve this problem

**Comment by Legowars10** [comment]
I'd like to reopen this, it's happening in version 2.4.2
