### ISSUE TITLE
[Feature Request] Add API Events

### ISSUE THREAD

**Issue by RickyLaChow** [nulli0n/CoinsEngine-spigot#21]
Add an event that contains the type of transaction, the player who carries it out, and the recipient, the amount, etc., or create different events for each transaction.

**Comment by nulli0n** [comment]
What transactions do you mean?

**Comment by RickyLaChow** [comment]
> What transactions do you mean?

-> /pay
-> /money giive

**Comment by dalmatheo** [comment]
I agree, you can make it so that it execute a spigot Event when the function changeBalance in CoinsUser is executed so that people can easily create plugins around your plugin

**Comment by dalmatheo** [comment]
#23

**Comment by RickyLaChow** [comment]
Any news about that?
