### ISSUE TITLE
Coins Engine API

### ISSUE THREAD

**Issue by isArkaDarkTime** [nulli0n/CoinsEngine-spigot#22]
Hello! I try this:
      <dependency>
          <groupId>su.nightexpress.coinsengine</groupId>
          <artifactId>CoinsEngine</artifactId>
          <version>2.3.0</version>
      </dependency>

but my maven return error:
`
su.nightexpress.coinsengine:CoinsEngine:pom:2.3.0 failed to transfer from https://https://repo.minebench.de/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of minebench has elapsed or updates are forced. Original error: Could not transfer artifact su.nightexpress.coinsengine:CoinsEngine:pom:2.3.0 from/to minebench (https://https://repo.minebench.de/): Этот хост неизвестен (https)

Try to run Maven import with -U flag (force update snapshots)
`

Get this info from: https://nightexpress.gitbook.io/coinsengine/utility/developer-api

**Comment by nulli0n** [comment]
You didn't install it properly.
