### ISSUE TITLE
Feature Request | Adding 2nd -s at end to silence console logging

### ISSUE THREAD

**Issue by Rexmen1** [nulli0n/CoinsEngine-spigot#25]
is there way to adding second -s at end to  silence console spam to coinsengine? /tokens give rexmen 1 -s -s
im using as tokens currency and tokens are given more like every second from activities, and 20-30 players spam will be too much

I do know there is way to fully silence all the currencies, but I have more 3 currencies and only want to silence 1 not all..

https://gyazo.com/736829ae41c2feaeb23f3bf99ab7c110

**Comment by Rexmen1** [comment]
hi

**Comment by nulli0n** [comment]
Ok will do

**Comment by nulli0n** [comment]
Added in v2.4.0
