### ISSUE TITLE
Disable number rounding

### ISSUE THREAD

**Issue by JuraRusan** [nulli0n/CoinsEngine-spigot#33]
Good day!

I am using a plugin to work with specific numbers and noticed that coins are being rounded. For example, when entering the command
`/gmcoin give dalandis 0.003`, 0 coins are added, and when using
`/gmcoin give dalandis 0.005`, 0.01 coins are added. In other words, rounding occurs.

I understand that these are very small amounts, and perhaps such numbers are not needed by anyone (except us…), and it may be technically difficult to process them correctly. However, I would like to have the ability to credit coins exactly as specified. If it is technically possible to implement this, that would be wonderful!

Alternatively, perhaps a setting in the configuration could allow rounding to be enabled or disabled.

Thank you!

**Comment by nulli0n** [comment]
Try with https://github.com/nulli0n/nightcore-spigot/releases/tag/v2.6.4
And set `Number_Format` in nightcore's config to `#,###.###`

**Comment by JuraRusan** [comment]
Thank you so much. Based on the release notes, it turns out the `Number_Format` function wasn’t working correctly, even though I had configured the value as `#,###.###`. I initially thought it wasn’t supported by the plugin. In any case, thank you. You've really helped us out!

Thank you!
