### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by EllenChang2132** [nulli0n/CoinsEngine-spigot#6]
I've seen your plugin "CoinsEngine on spigotmc, it's fantastic!!!!!
my spigot id is RaymondChang
I'm a Chinese server owner using the plugin. Could you please allow me to translate your plugin and advertise it to MCBBS? Many Chinese server owners want a translated language file, and I can help them. You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator. I'll show them your spigotmc page and let them download the plugin here. I'll NEVER claim it as mine, I just wanna translate it and let more people know it. I'll NEVER leak the jar file.
Hope for your reply!
And this plugin I search from mcbbs but no anything advertise this plugin
Please give advertise permission Please Sir
Thank You

**Comment by nulli0n** [comment]
Yes. Sorry for the late reply.
